version: '3'

services:
  wp:
    # user: '${UID}:${GID}'
    image: wordpress:latest # https://hub.docker.com/_/wordpress/
    # ports:
    #   - ${IP}:80:80 # change ip if required
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html # Full wordpress project
      #- ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
      # - ./theme-name/trunk/:/var/www/html/wp-content/themes/theme-name # Theme development
    networks:
      - traefik_default
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik_default'
      - 'traefik.http.routers.yourdomain-http.rule=Host(`${DOMAIN}`, `www.${DOMAIN}`)'

    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: '${DB_NAME}'
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: '${DB_ROOT_PASSWORD}'
    depends_on:
      - db
    links:
      - db

  wpcli:
    image: wordpress:cli
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
    labels:
      - 'traefik.enable=false'
      - 'traefik.docker.network=traefik_default'
    networks:
      - traefik_default
    depends_on:
      - db
      - wp

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
    ports:
      - ${IP}:5000:80
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik_default'
    links:
      - db:db
    networks:
      - traefik_default

  db:
    image: mysql:latest # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    ports:
      - ${IP}:3306:3306 # change ip if required
    labels:
      - 'traefik.enable=false'
      - 'traefik.docker.network=traefik_default'
    networks:
      - traefik_default
    command:
      [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
      ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'

volumes:
  db_data:
networks:
  traefik_default:
    external: true
